version: "3.9"
services:
  jupyterlab:
    image: marcpartensky/jupyterlab
    build:
      context: jupyterlab
      dockerfile: ./Dockerfile
  jupyterhub:
    image: marcpartensky/jupyterhub
    build:
      context: jupyterhub
      dockerfile: ./Dockerfile
