version: "3.9"
services:
  jupyterlab:
    image: marcpartensky/jupyterlab
    build:
      context: jupyterlab
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
  jupyterhub:
    image: marcpartensky/jupyterhub
    build:
      context: jupyterhub
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
